//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uDicom.WorkItemService.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("uDicom.WorkItemService.Common.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Route.
        /// </summary>
        public static string ActivityTypeEnumAutoRoute {
            get {
                return ResourceManager.GetString("ActivityTypeEnumAutoRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Series.
        /// </summary>
        public static string ActivityTypeEnumDeleteSeries {
            get {
                return ResourceManager.GetString("ActivityTypeEnumDeleteSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Study.
        /// </summary>
        public static string ActivityTypeEnumDeleteStudy {
            get {
                return ResourceManager.GetString("ActivityTypeEnumDeleteStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DICOM Receive.
        /// </summary>
        public static string ActivityTypeEnumDicomReceive {
            get {
                return ResourceManager.GetString("ActivityTypeEnumDicomReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DICOM Retrieve.
        /// </summary>
        public static string ActivityTypeEnumDicomRetrieve {
            get {
                return ResourceManager.GetString("ActivityTypeEnumDicomRetrieve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DICOM Send Series.
        /// </summary>
        public static string ActivityTypeEnumDicomSendSeries {
            get {
                return ResourceManager.GetString("ActivityTypeEnumDicomSendSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DICOM Send Images.
        /// </summary>
        public static string ActivityTypeEnumDicomSendSop {
            get {
                return ResourceManager.GetString("ActivityTypeEnumDicomSendSop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DICOM Send Study.
        /// </summary>
        public static string ActivityTypeEnumDicomSendStudy {
            get {
                return ResourceManager.GetString("ActivityTypeEnumDicomSendStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Files.
        /// </summary>
        public static string ActivityTypeEnumImportFiles {
            get {
                return ResourceManager.GetString("ActivityTypeEnumImportFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Study.
        /// </summary>
        public static string ActivityTypeEnumImportStudy {
            get {
                return ResourceManager.GetString("ActivityTypeEnumImportStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Files.
        /// </summary>
        public static string ActivityTypeEnumPublishFiles {
            get {
                return ResourceManager.GetString("ActivityTypeEnumPublishFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reapply Rules.
        /// </summary>
        public static string ActivityTypeEnumReapplyRules {
            get {
                return ResourceManager.GetString("ActivityTypeEnumReapplyRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-index.
        /// </summary>
        public static string ActivityTypeEnumReIndex {
            get {
                return ResourceManager.GetString("ActivityTypeEnumReIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Image Deleted.
        /// </summary>
        public static string DeleteProgress_Status {
            get {
                return ResourceManager.GetString("DeleteProgress_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Images Deleted.
        /// </summary>
        public static string DeleteProgressPlural_Status {
            get {
                return ResourceManager.GetString("DeleteProgressPlural_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Series.
        /// </summary>
        public static string DeleteSeriesRequest_ActivityDescription {
            get {
                return ResourceManager.GetString("DeleteSeriesRequest_ActivityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Study.
        /// </summary>
        public static string DeleteStudyRequest_ActivityDescription {
            get {
                return ResourceManager.GetString("DeleteStudyRequest_ActivityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Route to {0}.
        /// </summary>
        public static string DicomAutoRouteRequest_ActivityDescription {
            get {
                return ResourceManager.GetString("DicomAutoRouteRequest_ActivityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DICOM Receive from {0}.
        /// </summary>
        public static string DicomReceiveRequest_ActivityDescription {
            get {
                return ResourceManager.GetString("DicomReceiveRequest_ActivityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve of Study from {0}.
        /// </summary>
        public static string DicomRetreiveRequest_ActivityDescription {
            get {
                return ResourceManager.GetString("DicomRetreiveRequest_ActivityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve of Series from {0}.
        /// </summary>
        public static string DicomRetreiveSeriesRequest_ActivityDescription {
            get {
                return ResourceManager.GetString("DicomRetreiveSeriesRequest_ActivityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Images Retrieved, {1} Failed, {2} Pending.
        /// </summary>
        public static string DicomRetrieveProgress_Status {
            get {
                return ResourceManager.GetString("DicomRetrieveProgress_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Images Sent, {1} Failed, {2} Pending.
        /// </summary>
        public static string DicomSend_Status {
            get {
                return ResourceManager.GetString("DicomSend_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Images Sent, {1} Failed, {2} Pending.
        /// </summary>
        public static string DicomSendProgress_Status {
            get {
                return ResourceManager.GetString("DicomSendProgress_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DICOM Send to {0}.
        /// </summary>
        public static string DicomSendRequest_ActivityDescription {
            get {
                return ResourceManager.GetString("DicomSendRequest_ActivityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DICOM Send Series to {0}.
        /// </summary>
        public static string DicomSendSeriesRequest_ActivityDescription {
            get {
                return ResourceManager.GetString("DicomSendSeriesRequest_ActivityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DICOM Send Images to {0}.
        /// </summary>
        public static string DicomSendSopRequest_ActivityDescription {
            get {
                return ResourceManager.GetString("DicomSendSopRequest_ActivityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DICOM Send Study to {0}.
        /// </summary>
        public static string DicomSendStudyRequest_ActivityDescription {
            get {
                return ResourceManager.GetString("DicomSendStudyRequest_ActivityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} files imported, {2} failed.
        /// </summary>
        public static string ImportFilesProgress_Status {
            get {
                return ResourceManager.GetString("ImportFilesProgress_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import incomplete. {0} files imported..
        /// </summary>
        public static string ImportFilesProgress_StatusEnumerationIncomplete {
            get {
                return ResourceManager.GetString("ImportFilesProgress_StatusEnumerationIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing files for import from {0} location.
        /// </summary>
        public static string ImportFilesRequest_ActivityDescription {
            get {
                return ResourceManager.GetString("ImportFilesRequest_ActivityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing files for import from {0} locations.
        /// </summary>
        public static string ImportFilesRequest_ActivityDescriptionPlural {
            get {
                return ResourceManager.GetString("ImportFilesRequest_ActivityDescriptionPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Study.
        /// </summary>
        public static string ImportStudyRequest_AcitivityDescription {
            get {
                return ResourceManager.GetString("ImportStudyRequest_AcitivityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start reapply rules operation, possibly because a conflicting operation is currently running.  If this problem persists, please contact your system administrator..
        /// </summary>
        public static string MessageFailedToStartReapplyRules {
            get {
                return ResourceManager.GetString("MessageFailedToStartReapplyRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed..
        /// </summary>
        public static string Progress_Complete {
            get {
                return ResourceManager.GetString("Progress_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending..
        /// </summary>
        public static string Progress_Pending {
            get {
                return ResourceManager.GetString("Progress_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Files to {0}.
        /// </summary>
        public static string PublishFilesRequest_ActivityDescription {
            get {
                return ResourceManager.GetString("PublishFilesRequest_ActivityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} studies processed.
        /// </summary>
        public static string ReapplyRulesProgress_Status {
            get {
                return ResourceManager.GetString("ReapplyRulesProgress_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No studies found when reapplying rules..
        /// </summary>
        public static string ReapplyRulesProgress_StatusNoStudies {
            get {
                return ResourceManager.GetString("ReapplyRulesProgress_StatusNoStudies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-apply rule &apos;{0}&apos;.
        /// </summary>
        public static string ReapplyRulesRequest_ActivityDescription {
            get {
                return ResourceManager.GetString("ReapplyRulesRequest_ActivityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-apply multiple rules.
        /// </summary>
        public static string ReapplyRulesRequestMultiple_ActivityDescription {
            get {
                return ResourceManager.GetString("ReapplyRulesRequestMultiple_ActivityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} studies processed, {2} of {3} study folders processed, {4} studies deleted, {5} studies failed.
        /// </summary>
        public static string ReindexProgress_Status {
            get {
                return ResourceManager.GetString("ReindexProgress_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No studies found during reindex..
        /// </summary>
        public static string ReindexProgress_StatusNoStudies {
            get {
                return ResourceManager.GetString("ReindexProgress_StatusNoStudies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-index of the local file store.
        /// </summary>
        public static string ReindexRequest_ActivityDescription {
            get {
                return ResourceManager.GetString("ReindexRequest_ActivityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-index.
        /// </summary>
        public static string ReindexRequest_ActivityType {
            get {
                return ResourceManager.GetString("ReindexRequest_ActivityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute(s).
        /// </summary>
        public static string RetryDelayTimeUnitMinutes {
            get {
                return ResourceManager.GetString("RetryDelayTimeUnitMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second(s).
        /// </summary>
        public static string RetryDelayTimeUnitSeconds {
            get {
                return ResourceManager.GetString("RetryDelayTimeUnitSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry #{0} will occur at {1}.
        /// </summary>
        public static string RetryStatus {
            get {
                return ResourceManager.GetString("RetryStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} images processed, {2} failed.
        /// </summary>
        public static string StudyProcessProgress_Status {
            get {
                return ResourceManager.GetString("StudyProcessProgress_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string WorkItemPriorityEnumHigh {
            get {
                return ResourceManager.GetString("WorkItemPriorityEnumHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string WorkItemPriorityEnumNormal {
            get {
                return ResourceManager.GetString("WorkItemPriorityEnumNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stat.
        /// </summary>
        public static string WorkItemPriorityEnumStat {
            get {
                return ResourceManager.GetString("WorkItemPriorityEnumStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        public static string WorkItemStatusEnumCanceled {
            get {
                return ResourceManager.GetString("WorkItemStatusEnumCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping.
        /// </summary>
        public static string WorkItemStatusEnumCanceling {
            get {
                return ResourceManager.GetString("WorkItemStatusEnumCanceling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string WorkItemStatusEnumComplete {
            get {
                return ResourceManager.GetString("WorkItemStatusEnumComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string WorkItemStatusEnumDeleted {
            get {
                return ResourceManager.GetString("WorkItemStatusEnumDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete In Progress.
        /// </summary>
        public static string WorkItemStatusEnumDeleteInProgress {
            get {
                return ResourceManager.GetString("WorkItemStatusEnumDeleteInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string WorkItemStatusEnumFailed {
            get {
                return ResourceManager.GetString("WorkItemStatusEnumFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        public static string WorkItemStatusEnumIdle {
            get {
                return ResourceManager.GetString("WorkItemStatusEnumIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        public static string WorkItemStatusEnumInProgress {
            get {
                return ResourceManager.GetString("WorkItemStatusEnumInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string WorkItemStatusEnumPending {
            get {
                return ResourceManager.GetString("WorkItemStatusEnumPending", resourceCulture);
            }
        }
    }
}
